version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile.prod
    volumes:
      - ./client/dist:/client/dist
      - ./client/tsconfig.json:/client/tsconfig.json
    env_file:
      - ./client/docker/.prod.env
