version: "3.7"

services:
  api:
    container_name: api
    volumes:
      # set the container timezone to the time zone of host machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
