version: "3.7"

services:
  api:
    container_name: api
    image: ponomarevandrey/livestreamer-backend_api:latest
    # Uncomment to build the image for the first-time deployment (i.e. to 
    # upload to Docker Hub) or if you want to run prod env on local machine 
    # instead of VPS
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.prod
    tty: true
    restart: always
    ports:
      # Adding '127.0.0.1:' hides opened ports from Internet, 5000 is available
      # only in internal network on host machine
      - 127.0.0.1:5000:5000
    env_file:
      - ./api/docker/.common.env
      - ./api/docker/.prod.env
      - ./postgres/docker/.common.env
      - ./postgres/docker/.prod.env
    depends_on:
      - db
      - redis

  db:
    image: ponomarevandrey/livestreamer-backend_db:latest
    container_name: db
    # Uncomment to build the image for the first-time deployment (i.e. to 
    # upload to Docker Hub) or if you want to run prod env on local machine 
    # instead of VPS
    #build:
    #  context: ./postgres
    #  dockerfile: ./docker/Dockerfile.prod
    restart: always
    env_file:
      - ./postgres/docker/.common.env
      - ./postgres/docker/.prod.env
    volumes:
      - /var/backups/:/var/backups/
    ports:
      - 127.0.0.1:5432:5432
      
  redis:
    image: ponomarevandrey/livestreamer-backend_redis:latest
    container_name: redis
    # Uncomment to build the image for the first-time deployment (i.e. to 
    # upload to Docker Hub) or if you want to run prod env on local machine 
    # instead of VPS
    #build:
    #  context: ./redis
    #  dockerfile: ./docker/Dockerfile
    ports:
      - 127.0.0.1:6379:6379
