version: "3.7"

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: "no"
    env_file:
      - ./postgres/.dev.env
    # Publicly exposed ports (to simplify debugging)
    ports:
      - 54323:5432
    volumes:
      - ./postgres/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/02-create-first-app-user.sh:/docker-entrypoint-initdb.d/02-create-first-app-user.sh
