version: "3.7"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      # Main config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/html:/var/www/html
      # Server blocks config
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    #depends_on:
    #  - client
    #  - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      # set the same timezone and time same as on the host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
			# Recompile code on changes
      - ./api/src:/api/src
      - ./api/tsconfig.json:/api/tsconfig.json
      # Write live broadcast streams to disk
      - ./api/saved-streams:/api/saved-streams
    # Publicly exposed ports
    ports:
      # node.js process is listening for a debugging client on
      - 9230:9229
      # Delete this port after you spin up Nginx container as proxy, this port should not be public
      - 5000:5000
    # Ports not exposed publicly i.e. to host machine
    # (they are only exposed to other services)
    expose:
      # Node.js application server
      - 5000
    env_file:
      - ./.dev.common.env
      - ./api/.dev.env
      - ./postgres/.dev.env
  #    depends_on:
  #      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: "no"
    env_file:
      - ./postgres/.dev.env
    # Publicly exposed ports (to simplify debugging)
    ports:
      - 54323:5432
    volumes:
      - ./postgres/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/02-create-first-app-user.sh:/docker-entrypoint-initdb.d/02-create-first-app-user.sh

  redis:
    container_name: 'redis'
    image: redis
    volumes:
      - ./redis_data/:/opt/redis_data
    ports:
      - '6379:6379'

  client:
    container_name: client
    build: ./client
    restart: "always"
    volumes:
      - ./client/:/client/
    env_file:
      - ./.dev.common.env
      - ./client/.dev.env
    expose:
      - 3000
    # Publicly exposed ports (for development only). TODO: delete this port
    # after setting up Nginx
    ports:
      - 8080:8080
