version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    volumes:
      # Recompile code on changes
      - ./api/src:/api/src
      - ./api/_unit-tests_:/api/_unit-tests_
      - ./api/tsconfig.json:/api/tsconfig.json
      - /api/node_modules
    ports:
      # Port for the app
      - 5000:8080
      # node.js process is listening for a debugging client on
      - 9230:9229
    expose:
      # Port for the app (i.e. webpack dev server port)
      - 8080
    env_file:
      - ./api/docker/.common.env
      - ./api/docker/.dev.env
      - ./postgres/docker/.common.env
      - ./postgres/docker/.dev.env
    depends_on:
      - devdb
      - devredis
    networks:
      - livestreamer_backend

  devdb:
    container_name: devdb
    build:
      context: ./postgres
      dockerfile: ./docker/Dockerfile
    restart: "no"
    env_file:
      - ./postgres/docker/.common.env
      - ./postgres/docker/.dev.env
    ports:
      - 54324:5432
    # volumes:
    # Persist data outside container (useful if you need to edit config files)
    # - ./postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - livestreamer_backend

  devredis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: ./docker/Dockerfile
    #volumes:
    # Persist data outside container (useful if you need to edit config files)
    #  - ./redis/redis.conf:/redis.conf
    ports:
      - 6379:6379
    networks:
      - livestreamer_backend

networks:
  livestreamer_backend:
    name: livestreamer_backend
    driver: bridge
