version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.test
    restart: always
    tty: true
    volumes:
      # Recompile code on changes
      - ./api/src:/api/src
      - ./api/tsconfig.json:/api/tsconfig.json
      - ./api/_integration-tests_:/api/_integration-tests_
    ports:
      # Port for the app
      - 5001:8080
      # node.js process is listening for a debugging client on
      - 9230:9229      
    expose:
      # Port for the app
      - 5001
    env_file:
      - ./api/docker/.common.env
      - ./api/docker/.test.env
      - ./postgres/docker/.common.env
      - ./postgres/docker/.test.env
    depends_on:
      - testdb
      - testredis
    networks:
      - livestreamer_backend

  testdb:
    container_name: testdb
    build: 
      context: ./postgres
      dockerfile: ./docker/Dockerfile.test
    restart: "no"
    env_file:
      - ./postgres/docker/.common.env
      - ./postgres/docker/.test.env
    ports:
      - 54323:5432
    networks:
      - livestreamer_backend

  testredis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: ./docker/Dockerfile
    ports:
      - 6379:6379
    networks:
      - livestreamer_backend
      
networks:
  livestreamer_backend:
    name: livestreamer_backend
    driver: bridge
