version: "3.7"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile.prod
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./api/docker/.common.env
      - ./api/docker/.prod.env
      - ./postgres/docker/.common.env
      - ./postgres/docker/.prod.env
    depends_on:
      - db
      - redis

  db:
    container_name: streamer_db
    build:
      context: ./postgres
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file:
      - ./postgres/docker/.common.env
      - ./postgres/docker/.prod.env
    ports:
      - 5432:5432
      
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: ./docker/Dockerfile
    ports:
      - 6379:6379
