# DEV ENVIRONMENT

version: "3.7"

services:
  nginx:
    container_name: nginx
    build: ./../nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      # Main config
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../nginx/log/:/var/log/nginx/
      - ./../nginx/html:/var/www/html
      # Server blocks config
      - ./../nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - client
      - api
    expose:
      - 8000
    restart: "always"

  api:
    container_name: api
    build:
      context: ./../api
      dockerfile: ./docker/Dockerfile
    restart: "no"
    volumes:
      # set the same timezone and time same as on the host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Recompile code on changes
      - ./../api/src:/api/src
      - ./../api/unit-tests:/api/unit-tests
      - ./../api/integration-tests:/api/integration-tests
      - ./../api/tsconfig.json:/api/tsconfig.json
    # Publicly exposed ports
    ports:
      # node.js process is listening for a debugging client on
      - 9230:9229
      # Port to unit test websocket connection
      - 5001:5001
    # Ports not exposed publicly i.e. to host machine
    # (they are only exposed to other services)
    expose:
      # Node.js application server
      - 5000
      # Port to unit test websocket connection
      - 5001
    env_file:
      - ./.dev.common.env
      - ./../api/docker/.dev.env
      - ./../postgres/docker/.dev.env
    depends_on:
      - devdb
      - redis

  devdb:
    container_name: devdb
    image: postgres
    restart: "no"
    env_file:
      - ./../postgres/docker/.dev.env
    ports:
      - 54324:5432
    volumes:
      - ./../postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      # Files used by init.sh script
      - ./../postgres/schema:/schema
      - ./../postgres/seeds:/seeds

  redis:
    container_name: redis
    build:
      context: ./../redis
      dockerfile: Dockerfile
    volumes:
      - ./../redis/redis_data/:/opt/redis_data
      - ./../redis/redis.conf:/redis.conf
    ports:
      - 6379:6379

  client:
    container_name: client
    build:
      context: ./../client
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - ./../client/src/:/client/src
    env_file:
      - ./.dev.common.env
      - ./../client/docker/.dev.env
    expose:
      - 8081
    depends_on:
      - api
