name: CI

on:
  pull_request:
    branches: 
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.13.1]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test images for all services
        run: |
          cd livestreamer-backend/
          docker-compose --file ./docker-compose.test.yml up --detach
          docker exec -it api-test bash -c "npm run test:unit"