name: CI

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.13.1]
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Build images and start all containers
        run: |
          docker compose --file ./docker-compose.test.yml up --detach --build

      - name: Run Unit Tests
        run: docker exec -it api-test bash -c "npm run test:unit"

      - name: Stop containers
        if: always()
        run: docker compose --file ./docker-compose.test.yml down