name: CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  API_COMMON_ENV: ${{ vars.API_COMMON_ENV }}
  API_DEV_ENV: ${{ vars.API_DEV_ENV }}
  API_PROD_ENV: ${{ vars.API_PROD_ENV }}
  API_TEST_ENV: '${{ vars.API_TEST_ENV }}' 
  POSTGRES_COMMON_ENV: '${{ vars.POSTGRES_COMMON_ENV }}' 
  POSTGRES_DEV_ENV: '${{ vars.POSTGRES_DEV_ENV }}'
  POSTGRES_PROD_ENV: '${{ vars.POSTGRES_PROD_ENV }}'
  POSTGRES_TEST_ENV: '${{ vars.POSTGRES_TEST_ENV }}'    

jobs:

  dev:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 22.13.1
         cache: "npm"
     - run: cd ./api && npm ci
     - run: cd ./api && npm run ci:lint
     - run: cd ./api && npm run ci:prettify

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: ./ci/set-up-env-vars.sh
#      - run: ./ci/run-test-build.sh
    

